name: Generate assets

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run twice a day at 03:00 and 15:00 UTC / 12:00 and 00:00 JST
  schedule:
    - cron: '0 3,15 * * *'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      
      - name: Fetch existing assets
        run: |
          git fetch origin gh-pages:gh-pages --force
          git worktree add --detach assets gh-pages
        
      - name: Run
        env:
          SCRAPERAPI_API_KEY: ${{ secrets.SCRAPERAPI_API_KEY }}
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
        run: cargo run --release -- --download-images --yuyutei --tcgplayer --ogbajoj-sheet --official-hololive --gc
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: assets # The folder the action should deploy.
          clean: true
          commit-message: 'Update assets'