name: Generate assets

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run at 15:00 utc / 00:00 jst
  schedule:
    - cron: '0 15 * * *'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      
      - name: Copy cards info
        run: |
          mkdir assets --parents
          git fetch origin gh-pages:gh-pages --force
          git show gh-pages:hocg_cards.json > assets/hocg_cards.json
        
      - name: Run
        env:
          SCRAPERAPI_API_KEY: ${{ secrets.SCRAPERAPI_API_KEY }}
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
        run: cargo run --release -- --download-images --yuyutei --ogbajoj-sheet --official-hololive
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: assets # The folder the action should deploy.
          clean: false
          commit-message: 'Update assets'